baseURL = "https://www.aqa.ninja/"
languageCode = "en-us"
title = "AQA notes"
theme = "aqanja-theme"

[params]
  description = "Just a pet blog for sharing my AQA notes."
  
  [params.comments]
    enabled = true
    baseURL = "https://blog-backend-psi-rosy.vercel.app"