baseURL = "https://www.aqa.ninja" 
languageCode = "en-us"
title = "My Blog"
theme = "custom"

[params]
  description = "A proof of concept blog with comments"
  
  [params.comments]
    enabled = true
    baseURL = "blog-backend-psi-rosy.vercel.app"

languageCode = "en-us"